module.exports = {
  apps: [
    {
      name: "frontend",
      cwd: "./client",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
      },
      env_file: "./client/.env",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      ignore_watch: ["node_modules", "dist", ".git", "coverage"],
      max_memory_restart: "500M",
      error_file: "~/.pm2/logs/frontend-error.log",
      out_file: "~/.pm2/logs/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "30s",
    },

    {
      name: "backend",
      cwd: "./server",
      script: "npm",
      args: "run dev",
      env: {
        NODE_ENV: "development",
        PORT: 4000,
      },
      env_file: "./server/.env",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      ignore_watch: ["node_modules", "dist", ".git", "logs"],
      max_memory_restart: "300M",
      error_file: "~/.pm2/logs/backend-error.log",
      out_file: "~/.pm2/logs/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "30s",
      kill_timeout: 5000,
    },

    {
      name: "worker",
      cwd: "./server",
      script: "npm",
      args: "run worker:dev",
      env: {
        NODE_ENV: "development",
      },
      env_file: "./server/.env",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      ignore_watch: ["node_modules", "dist", ".git", "logs"],
      max_memory_restart: "300M",
      error_file: "~/.pm2/logs/worker-error.log",
      out_file: "~/.pm2/logs/worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "30s",
      kill_timeout: 5000,
    },
  ],
};
