export const plans = [
  {
    name: "Starter",
    price: "$19",
    period: "/mo per seat",
    tagline: "Perfect for small teams getting started.",
    highlight: false,
    badge: null,
    ctaVariant: "outline" as const,
    cta: "Start free",
    features: [
      "Up to 500 leads/month",
      "3 pipeline stages",
      "Basic analytics dashboard",
      "Email notifications",
      "1 tenant",
      "Community support",
    ],
  },
  {
    name: "Pro",
    price: "$49",
    period: "/mo per seat",
    tagline: "For growing sales teams that need real automation.",
    highlight: true,
    badge: "Most popular",
    ctaVariant: "default" as const,
    cta: "Start free trial",
    features: [
      "Unlimited leads",
      "Custom pipeline stages",
      "Real-time analytics + exports",
      "Workflow automation",
      "Multi-tenant (up to 10)",
      "Round-robin assignment",
      "Slack + webhook actions",
      "Priority support",
    ],
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "",
    tagline: "For orgs that need full control and compliance.",
    highlight: false,
    badge: null,
    ctaVariant: "outline" as const,
    cta: "Talk to sales",
    features: [
      "Everything in Pro",
      "Unlimited tenants",
      "SSO / SAML",
      "Audit logs",
      "SLA guarantee",
      "Dedicated onboarding",
      "Custom integrations",
      "99.99% uptime SLA",
    ],
  },
];
