export const LEAD_ACTIVITY_TYPES = {
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  STATUS_CHANGED: "STATUS_CHANGED",
  SCORE_UPDATED: "SCORE_UPDATED",
  COMMENT_ADDED: "COMMENT_ADDED",
  COMMENT_DELETED: "COMMENT_DELETED",
  CALL_ADDED: "CALL_ADDED",
  CALL_DELETED: "CALL_DELETED",
  ATTACHMENT_ADDED: "ATTACHMENT_ADDED",
  ATTACHMENT_REMOVED: "ATTACHMENT_REMOVED",
  CONVERTED_TO_DEAL: "CONVERTED_TO_DEAL",
  ASSIGNED: "assigned",
};
